### ISSUE TITLE
Error: kallisto index file not found kallisto_index

### ISSUE THREAD

**Issue by wbvguo** [signalbash/how_are_we_stranded_here#13]
Hello, I tried to get this tool running but encounter an issue. The following are the code and error message that I got:

Code:
`check_strandedness --gtf ref/Mus_musculus.GRCm38.93.gtf --transcripts ref/Mus_musculus.GRCm38.cdna.all.fa --reads_1 reads/test_R1.fastq.gz --reads_2 reads/test_R2.fastq.gz`

Output error:
```
Error: kallisto index file not found kallisto_index

Usage: kallisto quant [arguments] FASTQ-files

...
xxxxxxxx/kallisto_strand_test/pseudoalignments.bam does NOT exists.
Traceback (most recent call last):
  File "xxxxxxxx/check_strandedness", line 8, in <module>
    sys.exit(main())
  File "xxxxxxxx/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "xxxxxxxx/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "xxxxxxxx/site-packages/pandas/io/parsers/readers.py", line 665, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "xxxxxxxx/site-packages/pandas/io/parsers/readers.py", line 1538, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.
```

Such a problem seems to appear in the previous post: issue #10 .

The software version on my side is:
how-are-we-stranded-here  1.0.1 
rseqc                     4.0.0
kallisto                  0.48.0  
python                    3.10.5

**Comment by KuechlerO** [comment]
For me it worked with this Conda-environment:
```
name: test_strandedness_env
channels:
  - bioconda
  - default
  - conda-forge
dependencies:
  - python=3.6
  - kallisto=0.44.0
  - rseqc
  - pip:
    - how-are-we-stranded-here==1.0.1
    - pandas
```

However, I also performed the computations on a cluster, and the process was there always killed with cryptic messages. Finally I figured out, that a significant amount of RAM is needed for this process (I suspect Kallisto to be the origin of that problem). Thus, for me dedicating enough memory to the function call was the key! (2 GBs were not enough, but 8 GBs worked out fine.)

**Comment by ghost** [comment]
Hello @wbvguo . I'm currently facing the exact same issue. Were you able to solve it?

**Comment by wbvguo** [comment]
Hi @adinanadeem, I did not try to solve it.

**Comment by khatch88** [comment]
I had a similar issue, still due to pandas but it did not seem to be the in the kallisto index:

Traceback (most recent call last):
  File "/home/khatch/miniconda3/envs/rna_prac/bin/check_strandedness", line 10, in <module>
    sys.exit(main())
  File "/home/khatch/miniconda3/envs/rna_prac/lib/python3.10/site-packages/how_are_we_stranded_here/check_strandedness.py", line 185, in main
    result = pd.read_csv(test_folder + '/' + 'strandedness_check.txt', sep="\n", header=None)
  File "/home/khatch/miniconda3/envs/rna_prac/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/khatch/miniconda3/envs/rna_prac/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/khatch/miniconda3/envs/rna_prac/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 935, in read_csv
    kwds_defaults = _refine_defaults_read(
  File "/home/khatch/miniconda3/envs/rna_prac/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 2063, in _refine_defaults_read
    raise ValueError(
ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator.Hence it is not allowed to use the line terminator as separator.
