### ISSUE TITLE
NameError when converting gtf to bed

### ISSUE THREAD

**Issue by sarah872** [signalbash/how_are_we_stranded_here#9]
Hi!

I am trying to run
```
check_strandedness -g file.gtf -fa file.fasta -r1 R1.fq.gz -r2 .R2.fq.gz
```
But I'm getting the following error during the step of converting the gtf to bed:

```
Results stored in: stranded_test_R1_1
converting gtf to bed
Traceback (most recent call last):
  File "/conda-how_are_we_stranded_here/bin/gtf2bed", line 8, in <module>
    sys.exit(main())
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/how_are_we_stranded_here/gtf2bed.py", line 76, in main
    write_bed_line()
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/how_are_we_stranded_here/gtf2bed.py", line 20, in write_bed_line
    starts_array = np.array(starts)
NameError: free variable 'starts' referenced before assignment in enclosing scope
Checking if fasta headers and bed file transcript_ids match...
Can't find transcript ids from file.fasta in stranded_test_R1_1/file.bed
Trying to converting fasta header format to match transcript ids to the BED file...
Can't find any of the first 10 BED transcript_ids in fasta file... Check that these match
```

I'm using Python 3.7.12.
Could you provide the example files, to see if everything is ok on your side? It could be that my gtf file is not correct.

UPDATE:
I was trying with a gff file, but I'm getting an error here too:

```
Results stored in: stranded_test_R1
converting gff to gtf
Traceback (most recent call last):
  File "/conda-how_are_we_stranded_here/bin/gff32gtf", line 8, in <module>
    sys.exit(main())
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/how_are_we_stranded_here/gff32gtf.py", line 55, in main
    gff3.loc[gff3.type=='gene','gene_id'] = gff3.loc[gff3.type=='gene','attributes'].str.split("ID=").str[1].str.split(";").str[0]
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
converting gtf to bed
Traceback (most recent call last):
  File "/conda-how_are_we_stranded_here/bin/gtf2bed", line 8, in <module>
    sys.exit(main())
  File "/conda-how_are_we_stranded_here/lib/python3.7/site-packages/how_are_we_stranded_here/gtf2bed.py", line 38, in main
    for lines in open(args.gtf):
FileNotFoundError: [Errno 2] No such file or directory: 'stranded_test_R1/file.gtf'
Checking if fasta headers and bed file transcript_ids match...
Can't find transcript ids from file.fasta in stranded_test_R1/file.bed
Trying to converting fasta header format to match transcript ids to the BED file...
Can't find any of the first 10 BED transcript_ids in fasta file... Check that these match
```

**Comment by signalbash** [comment]
Same as https://github.com/signalbash/how_are_we_stranded_here/issues/8

Fixed in https://github.com/signalbash/how_are_we_stranded_here/commit/0fedf9245c3bbbcdf670e2b374196ca5d40cab25
